[project]
name = "kf1-mods-installer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mythical-Github", email = "67753356+Mythical-Github@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "kf1-mods-installer-core",
]

[project.scripts]
kf1_mods_installer = "kf1_mods_installer.main:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
kf1-mods-installer-core = { git = "https://github.com/KillingFloorSeriesModding/kf1-mods-installer-core" }

[dependency-groups]
dev = [
    "pyinstaller>=6.22.2",
]
